FROM i386/debian

ARG USER_ID=1000
ARG GROUP_ID=1000
ARG USERNAME=smitty

RUN apt update
RUN apt install -y vim git tmux build-essential screen procps net-tools tcpdump libasound2 libasound2-dev alsa-utils

# Create a group and user with the specified UID and GID
RUN groupadd -g ${GROUP_ID} ${USERNAME} && \
    useradd -m -u ${USER_ID} -g ${USERNAME} -s /bin/bash ${USERNAME} && \
    echo "${USERNAME} ALL=(ALL) NOPASSWD:ALL" >> /etc/sudoers

# Switch to the new user
USER ${USERNAME}

# Set the working directory
WORKDIR /home/${USERNAME}
